name: Deploy Frontend to Azure Web App

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
      - cicd

defaults:
  run:
    working-directory: frontend

env:
  node-version: 14.x
  appName: ${{ secrets.AzureAppService_AppName }}-frontend
  NEXT_PUBLIC_APP_VERSION: $GITHUB_RUN_ID/$GITHUB_ACTION

jobs:
  frontend-deploy:
    name: Deploy Frontend to Azure Web App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ env.node-version }}

      - name: Build Frontend
        run: |
          npm ci
          npm run build --if-present
          rm -rf node_modules

      - name: "Deploy Frontend to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.appName }}
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_Frontend }}
          package: frontend
