
name: CodeCov Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - run: npm t
        working-directory: frontend
        
      - name: Codeco
        uses: codecov/codecov-action@v1.2.1
        with:
          working-directory: frontend
